name: Atualizar oportunidades

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Executar crawler
        run: python main.py

      - name: Commit resultados
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add oportunidades.json
          git commit -m "Atualização automática"
          git push
